name: Merge check 

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 22
      uses: actions/setup-java@v4
      with:
        java-version: '22'
        distribution: 'temurin'
        cache: maven
    - name: Stop and remove old container
      run: |
        docker stop finApi || true
        docker rm finApi || true
        
    - name: Build with Maven
      run: mvn clean package -DskipTests

    - name: Build Docker image
      run: docker build -t finbe:latest .

    - name: Deploy Docker container
      run: docker run -d -p 8083:8083 --name finApi -e SPRING_DATASOURCE_URL=jdbc:mysql://172.17.0.2:3306/finv2 -e SPRING_DATASOURCE_USERNAME=neng -e SPRING_DATASOURCE_PASSWORD=mypassword finbe:latest
